import re

def encontrar_posicion_regex(input):#cadena, palabra
    for case in input:
        res = {
            'text': case[0],
            "entities": [],
        }
        
        labels = case[1]
        for label, palabra in labels.items():
            patron = re.escape(palabra)  # Escapar palabra para caracteres especiales
            coincidencia = re.search(patron, case[0])
            if coincidencia:
                res['entities'].append((coincidencia.start(), coincidencia.end(),label))
          
        print(res)

training_data = [
    ["buenas tardes, quisiera cotizar un seguro para mi auto por favor, envíenme las diferentes opciones que su compañia ofrece los datos de mi vehiculo son  marca chevrolet  modelo spin  año 2023 cod postal 1414  tengo cochera propia adjunto también foto de mi vehiculo para que se vea que está en perfectas condiciones muchas gracias",
    {'MARCA': 'chevrolet', 'MODELO':'spin', 'AÑO': '2023', 'COD_POSTAL':'1414'}],
    ["hola, necesito un seguro para mi auto marca ford modelo fiesta año 2019 código postal 5000 gracias",
    {'MARCA': 'ford', 'MODELO':'fiesta', 'AÑO': '2019','COD_POSTAL': '5000'}],
    ["buen día, quisiera saber cuánto me cuesta un seguro para mi coche marca toyota modelo corolla año 2015 cod. postal 2442 gracias",
     {'MARCA': 'toyota', 'MODELO':'corolla', 'AÑO': '2015','COD_POSTAL': '2442'}],
    ["necesito asegurar mi vehículo, es un honda civic del año 2020, código postal 2420",
     {'MARCA': 'honda', 'MODELO':'civic', 'AÑO': '2020','COD_POSTAL': '2420'}],
    ["buenos días, quisiera información sobre seguros para un nissan sentra del 2018, vivo en el código postal 12345",
      {'MARCA': 'nissan', 'MODELO':'sentra', 'AÑO': '2018','COD_POSTAL': '12345'}],
    ["quiero asegurar un auto marca peugeot modelo 208 año 2021, mi código postal es 4321",
     {'MARCA': 'peugeot', 'MODELO':'208', 'AÑO': '2021','COD_POSTAL': '4321'}],
    ["hola, estoy buscando opciones de seguro para un volkswagen gol del año 2017, código postal 7651",
     {'MARCA': 'volkswagen', 'MODELO':'gol', 'AÑO': '2017','COD_POSTAL': '7651'}],
    ["saludos, necesito un seguro para mi automóvil marca bmw modelo serie 3 año 2016 cod postal 1134",
     {'MARCA': 'bmw', 'MODELO':'serie 3', 'AÑO': '2016','COD_POSTAL': '1134'}],
    ["buenas noches, quisiera información para asegurar un kia rio del 2014, código postal 3451",
     {'MARCA': 'kio', 'MODELO':'rio', 'AÑO': '2014','COD_POSTAL': '3451'}],
    ["Hola, necesito asegurar un toyota corolla del 2018, mi código postal es 1425", 
    {'MARCA': 'toyota', 'MODELO':'corolla', 'AÑO': '2018', 'COD_POSTAL': '1425'}],
    ["Quisiera una cotización para asegurar un honda civic del 2020, código postal 1406", 
    {'MARCA': 'honda', 'MODELO':'civic', 'AÑO': '2020', 'COD_POSTAL': '1406'}],
    ["Buenas tardes, pueden darme información para asegurar un ford mustang del 2015, vivo en el área de código postal 1001", 
    {'MARCA': 'ford', 'MODELO':'mustang', 'AÑO': '2015', 'COD_POSTAL': '1001'}],
    ["Mi código postal es 1430, quiero asegurar un chevrolet onix del 2019", 
    {'MARCA': 'chevrolet', 'MODELO':'onix', 'AÑO': '2019', 'COD_POSTAL': '1430'}],
    ["Hola, necesito asegurar un toyota corolla del 2018, mi código postal es 1425",
    {'MARCA': 'toyota', 'MODELO': 'corolla', 'AÑO': '2018', 'COD_POSTAL': '1425'}],
    ["Quisiera una cotización para asegurar un honda civic del 2020, código postal 1406",
    {'MARCA': 'honda', 'MODELO': 'civic', 'AÑO': '2020', 'COD_POSTAL': '1406'}],
    ["Buenas tardes, pueden darme información para asegurar un ford mustang del 2015, vivo en el área de código postal 1001",
    {'MARCA': 'ford', 'MODELO': 'mustang', 'AÑO': '2015', 'COD_POSTAL': '1001'}],
    ["Mi código postal es 1430, quiero asegurar un chevrolet onix del 2019",
    {'MARCA': 'chevrolet', 'MODELO': 'onix', 'AÑO': '2019', 'COD_POSTAL': '1430'}],
    ["Necesito cotizar el seguro para un fiat punto del 2017, vivo en el código postal 1428",
    {'MARCA': 'fiat', 'MODELO': 'punto', 'AÑO': '2017', 'COD_POSTAL': '1428'}],
    ["Mi código postal es 1416 y necesito asegurar un renault clio del 2016",
    {'MARCA': 'renault', 'MODELO': 'clio', 'AÑO': '2016', 'COD_POSTAL': '1416'}],
    ["Vivo en el código postal 1408, quisiera información para asegurar un peugeot 208 del 2018",
    {'MARCA': 'peugeot', 'MODELO': '208', 'AÑO': '2018', 'COD_POSTAL': '1408'}],
    ["Quiero asegurar un volkswagen golf del 2020, mi código postal es 1440",
    {'MARCA': 'volkswagen', 'MODELO': 'golf', 'AÑO': '2020', 'COD_POSTAL': '1440'}],
    ["Mi código postal es 1429, estoy buscando asegurar un nissan versa del 2019",
    {'MARCA': 'nissan', 'MODELO': 'versa', 'AÑO': '2019', 'COD_POSTAL': '1429'}],
    ["Necesito información sobre el seguro para un bmw serie 3 del 2021, código postal 1414",
    {'MARCA': 'bmw', 'MODELO': 'serie 3', 'AÑO': '2021', 'COD_POSTAL': '1414'}],
    ["Vivo en el código postal 1405 y quiero asegurar un audi a4 del 2015",
    {'MARCA': 'audi', 'MODELO': 'a4', 'AÑO': '2015', 'COD_POSTAL': '1405'}],
    ["Mi código postal es 1437, necesito asegurar un mercedes-benz clase c del 2017",
    {'MARCA': 'mercedes-benz', 'MODELO': 'clase c', 'AÑO': '2017', 'COD_POSTAL': '1437'}],
    ["Hola, quiero cotizar el seguro para un hyundai tucson del 2018, mi código postal es 1424",
    {'MARCA': 'hyundai', 'MODELO': 'tucson', 'AÑO': '2018', 'COD_POSTAL': '1424'}],
    ["Busco información para asegurar un citroën c3 del 2022, vivo en el código postal 1417",
    {'MARCA': 'citroën', 'MODELO': 'c3', 'AÑO': '2022', 'COD_POSTAL': '1417'}],
     ["Código postal 1426, quiero asegurar un Ford Fiesta del 2017",
    {'MARCA': 'Ford', 'MODELO': 'Fiesta', 'AÑO': '2017', 'COD_POSTAL': '1426'}],
    ["Vivo en el código postal 1407, necesito asegurar un toyota hilux del 2015",
    {'MARCA': 'toyota', 'MODELO': 'hilux', 'AÑO': '2015', 'COD_POSTAL': '1407'}],
    ["Quiero asegurar un Renault Duster del 2020, mi código postal es 1420",
    {'MARCA': 'Renault', 'MODELO': 'Duster', 'AÑO': '2020', 'COD_POSTAL': '1420'}],
    ["Necesito cotizar el seguro para un kia sportage del 2018, vivo en el código postal 1418",
    {'MARCA': 'kia', 'MODELO': 'sportage', 'AÑO': '2018', 'COD_POSTAL': '1418'}],
    ["Mi código postal es 1431, quiero asegurar un Peugeot 308 del 2019",
    {'MARCA': 'Peugeot', 'MODELO': '308', 'AÑO': '2019', 'COD_POSTAL': '1431'}],
    ["Vivo en el código postal 1409 y quiero asegurar un ford focus del 2016",
    {'MARCA': 'ford', 'MODELO': 'focus', 'AÑO': '2016', 'COD_POSTAL': '1409'}],
    ["Busco información para asegurar un Chevrolet Tracker del 2021, mi código postal es 1410",
    {'MARCA': 'Chevrolet', 'MODELO': 'Tracker', 'AÑO': '2021', 'COD_POSTAL': '1410'}],
    ["Mi código postal es 1422, necesito asegurar un Honda CR-V del 2017",
    {'MARCA': 'Honda', 'MODELO': 'CR-V', 'AÑO': '2017', 'COD_POSTAL': '1422'}],
    ["Quiero asegurar un volkswagen t-cross del 2019, código postal 1412",
    {'MARCA': 'volkswagen', 'MODELO': 't-cross', 'AÑO': '2019', 'COD_POSTAL': '1412'}],
    ["Código postal 1442, necesito asegurar un Toyota RAV4 del 2020",
    {'MARCA': 'Toyota', 'MODELO': 'RAV4', 'AÑO': '2020', 'COD_POSTAL': '1442'}],
    ["Mi código postal es 1435, quiero asegurar un fiat toro del 2018",
    {'MARCA': 'fiat', 'MODELO': 'toro', 'AÑO': '2018', 'COD_POSTAL': '1435'}],
    ["Vivo en el código postal 1421 y necesito asegurar un Nissan Sentra del 2016",
    {'MARCA': 'Nissan', 'MODELO': 'Sentra', 'AÑO': '2016', 'COD_POSTAL': '1421'}],
    ["Busco información para asegurar un BMW X1 del 2019, mi código postal es 1404",
    {'MARCA': 'BMW', 'MODELO': 'X1', 'AÑO': '2019', 'COD_POSTAL': '1404'}],
    ["Necesito asegurar un Audi Q3 del 2017, mi código postal es 1413",
    {'MARCA': 'Audi', 'MODELO': 'Q3', 'AÑO': '2017', 'COD_POSTAL': '1413'}],
    ["Mi código postal es 1423, quiero asegurar un Citroën C4 del 2020",
    {'MARCA': 'Citroën', 'MODELO': 'C4', 'AÑO': '2020', 'COD_POSTAL': '1423'}],
    ["Código postal 1434, necesito asegurar un Mercedes-Benz GLA del 2018",
    {'MARCA': 'Mercedes-Benz', 'MODELO': 'GLA', 'AÑO': '2018', 'COD_POSTAL': '1434'}],
    ["Vivo en el código postal 1401, quiero asegurar un kia rio del 2015",
    {'MARCA': 'kia', 'MODELO': 'rio', 'AÑO': '2015', 'COD_POSTAL': '1401'}],
    ["Mi código postal es 1436 y necesito asegurar un Renault Sandero del 2021",
    {'MARCA': 'Renault', 'MODELO': 'Sandero', 'AÑO': '2021', 'COD_POSTAL': '1436'}],
    ["Quiero asegurar un ford ranger del 2017, mi código postal es 1441",
    {'MARCA': 'ford', 'MODELO': 'ranger', 'AÑO': '2017', 'COD_POSTAL': '1441'}],
    ["Busco información para asegurar un Peugeot 2008 del 2016, mi código postal es 1427",
    {'MARCA': 'Peugeot', 'MODELO': '2008', 'AÑO': '2016', 'COD_POSTAL': '1427'}],
    ["Código postal 1432, necesito asegurar un Hyundai Creta del 2019",
    {'MARCA': 'Hyundai', 'MODELO': 'Creta', 'AÑO': '2019', 'COD_POSTAL': '1432'}],
    ["Vivo en el código postal 1403 y quiero asegurar un Volkswagen Tiguan del 2018",
    {'MARCA': 'Volkswagen', 'MODELO': 'Tiguan', 'AÑO': '2018', 'COD_POSTAL': '1403'}],
    ["Mi código postal es 1415, quiero asegurar un Audi A3 del 2015",
    {'MARCA': 'Audi', 'MODELO': 'A3', 'AÑO': '2015', 'COD_POSTAL': '1415'}],
    ["Busco información para asegurar un Ford Kuga del 2020, mi código postal es 1426",
    {'MARCA': 'Ford', 'MODELO': 'Kuga', 'AÑO': '2020', 'COD_POSTAL': '1426'}],
    ["Quiero asegurar un toyota yaris del 2017, mi código postal es 1433",
    {'MARCA': 'toyota', 'MODELO': 'yaris', 'AÑO': '2017', 'COD_POSTAL': '1433'}],
    ["Código postal 1402, necesito asegurar un Kia Seltos del 2016",
    {'MARCA': 'Kia', 'MODELO': 'Seltos', 'AÑO': '2016', 'COD_POSTAL': '1402'}],
    ["Vivo en el código postal 1439, quiero asegurar un Renault Captur del 2018",
    {'MARCA': 'Renault', 'MODELO': 'Captur', 'AÑO': '2018', 'COD_POSTAL': '1439'}],
    ["Busco información para asegurar un Volkswagen Jetta del 2017, mi código postal es 1443",
    {'MARCA': 'Volkswagen', 'MODELO': 'Jetta', 'AÑO': '2017', 'COD_POSTAL': '1443'}],
    ["Mi código postal es 1419 y necesito asegurar un Peugeot 208 del 2019",
    {'MARCA': 'Peugeot', 'MODELO': '208', 'AÑO': '2019', 'COD_POSTAL': '1419'}],
    ["Quiero asegurar un Chevrolet Cruze del 2018, mi código postal es 1424",
    {'MARCA': 'Chevrolet', 'MODELO': 'Cruze', 'AÑO': '2018', 'COD_POSTAL': '1424'}],
    ["Código postal 1408, necesito asegurar un Mercedes-Benz Clase A del 2021",
    {'MARCA': 'Mercedes-Benz', 'MODELO': 'Clase A', 'AÑO': '2021', 'COD_POSTAL': '1408'}],
    ["Vivo en el código postal 1438, quiero asegurar un Nissan Kicks del 2020",
    {'MARCA': 'Nissan', 'MODELO': 'Kicks', 'AÑO': '2020', 'COD_POSTAL': '1438'}],
    ["Busco información para asegurar un Ford EcoSport del 2017, mi código postal es 1405",
    {'MARCA': 'Ford', 'MODELO': 'EcoSport', 'AÑO': '2017', 'COD_POSTAL': '1405'}],
    ["Mi código postal es 1421 y quiero asegurar un Renault Koleos del 2016",
    {'MARCA': 'Renault', 'MODELO': 'Koleos', 'AÑO': '2016', 'COD_POSTAL': '1421'}],
    ["Quiero asegurar un Volkswagen Passat del 2019, mi código postal es 1430",
    {'MARCA': 'Volkswagen', 'MODELO': 'Passat', 'AÑO': '2019', 'COD_POSTAL': '1430'}],
    ["Código postal 1416, necesito asegurar un Peugeot 3008 del 2018",
    {'MARCA': 'Peugeot', 'MODELO': '3008', 'AÑO': '2018', 'COD_POSTAL': '1416'}],
    ["Vivo en el código postal 1444, quiero asegurar un Audi Q5 del 2020",
    {'MARCA': 'Audi', 'MODELO': 'Q5', 'AÑO': '2020', 'COD_POSTAL': '1444'}],
    ["Busco información para asegurar un Toyota Etios del 2017, mi código postal es 1420",
    {'MARCA': 'Toyota', 'MODELO': 'Etios', 'AÑO': '2017', 'COD_POSTAL': '1420'}],
    ["Mi código postal es 1406 y necesito asegurar un Nissan March del 2016",
    {'MARCA': 'Nissan', 'MODELO': 'March', 'AÑO': '2016', 'COD_POSTAL': '1406'}],
    ["Quiero asegurar un Ford Mondeo del 2018, mi código postal es 1417",
    {'MARCA': 'Ford', 'MODELO': 'Mondeo', 'AÑO': '2018', 'COD_POSTAL': '1417'}],
    ["Código postal 1431, necesito asegurar un Chevrolet Onix del 2021",
    {'MARCA': 'Chevrolet', 'MODELO': 'Onix', 'AÑO': '2021', 'COD_POSTAL': '1431'}],
    ["Vivo en el código postal 1445 y quiero asegurar un Kia Picanto del 2019",
    {'MARCA': 'Kia', 'MODELO': 'Picanto', 'AÑO': '2019', 'COD_POSTAL': '1445'}],
    ["Busco información para asegurar un Renault Kangoo del 2017, mi código postal es 1428",
    {'MARCA': 'Renault', 'MODELO': 'Kangoo', 'AÑO': '2017', 'COD_POSTAL': '1428'}],
    ["Mi código postal es 1407 y quiero asegurar un Peugeot 208 del 2016",
    {'MARCA': 'Peugeot', 'MODELO': '208', 'AÑO': '2016', 'COD_POSTAL': '1407'}],
    ["Quiero asegurar un Ford Fiesta del 2019, mi código postal es 1418",
    {'MARCA': 'Ford', 'MODELO': 'Fiesta', 'AÑO': '2019', 'COD_POSTAL': '1418'}],
    ["Código postal 1432, necesito asegurar un Volkswagen Up del 2017",
    {'MARCA': 'Volkswagen', 'MODELO': 'Up', 'AÑO': '2017', 'COD_POSTAL': '1432'}],
    ["Vivo en el código postal 1409, quiero asegurar un Toyota Corolla del 2018",
    {'MARCA': 'Toyota', 'MODELO': 'Corolla', 'AÑO': '2018', 'COD_POSTAL': '1409'}],
    ["Busco información para asegurar un Honda Fit del 2016, mi código postal es 1425",
    {'MARCA': 'Honda', 'MODELO': 'Fit', 'AÑO': '2016', 'COD_POSTAL': '1425'}],
    ["Mi código postal es 1440 y necesito asegurar un Chevrolet Spin del 2020",
    {'MARCA': 'Chevrolet', 'MODELO': 'Spin', 'AÑO': '2020', 'COD_POSTAL': '1440'}],
    ["Quiero asegurar un Renault Logan del 2017, mi código postal es 1411",
    {'MARCA': 'Renault', 'MODELO': 'Logan', 'AÑO': '2017', 'COD_POSTAL': '1411'}],
    ["Código postal 1433, necesito asegurar un Peugeot 408 del 2018",
    {'MARCA': 'Peugeot', 'MODELO': '408', 'AÑO': '2018', 'COD_POSTAL': '1433'}],
    ["Vivo en el código postal 1446 y quiero asegurar un Nissan Versa del 2021",
    {'MARCA': 'Nissan', 'MODELO': 'Versa', 'AÑO': '2021', 'COD_POSTAL': '1446'}],
    ["Busco información para asegurar un BMW Serie 1 del 2019, mi código postal es 1408",
    {'MARCA': 'BMW', 'MODELO': 'Serie 1', 'AÑO': '2019', 'COD_POSTAL': '1408'}],
    ["Mi código postal es 1414 y quiero asegurar un Toyota Yaris del 2017",
    {'MARCA': 'Toyota', 'MODELO': 'Yaris', 'AÑO': '2017', 'COD_POSTAL': '1414'}],
    ["Quiero asegurar un Mercedes-Benz Clase C del 2018, mi código postal es 1422",
    {'MARCA': 'Mercedes-Benz', 'MODELO': 'Clase C', 'AÑO': '2018', 'COD_POSTAL': '1422'}],
    ["Código postal 1437, necesito asegurar un Kia Sportage del 2016",
    {'MARCA': 'Kia', 'MODELO': 'Sportage', 'AÑO': '2016', 'COD_POSTAL': '1437'}],
    ["Vivo en el código postal 1447, quiero asegurar un Ford Mustang del 2019",
    {'MARCA': 'Ford', 'MODELO': 'Mustang', 'AÑO': '2019', 'COD_POSTAL': '1447'}],
    ["Hola, quiero cotizar el seguro para un volkswagen gol del 2019, mi código postal es 1415",
    {'MARCA': 'volkswagen', 'MODELO': 'gol', 'AÑO': '2019', 'COD_POSTAL': '1415'}],
    ["Quiero asegurar un toyota yaris del 2017, mi código postal es 1433",
    {'MARCA': 'toyota', 'MODELO': 'yaris', 'AÑO': '2017', 'COD_POSTAL': '1433'}],
    ["Código postal 1402, necesito asegurar un kia picanto del 2016",
    {'MARCA': 'kia', 'MODELO': 'picanto', 'AÑO': '2016', 'COD_POSTAL': '1402'}],
    ["Vivo en el código postal 1421 y quiero asegurar un renault koleos del 2016",
    {'MARCA': 'renault', 'MODELO': 'koleos', 'AÑO': '2016', 'COD_POSTAL': '1421'}],
    ["Busco información para asegurar un volkswagen t-cross del 2019, mi código postal es 1412",
    {'MARCA': 'volkswagen', 'MODELO': 't-cross', 'AÑO': '2019', 'COD_POSTAL': '1412'}],
    ["Mi código postal es 1423, necesito asegurar un peugeot 308 del 2020",
    {'MARCA': 'peugeot', 'MODELO': '308', 'AÑO': '2020', 'COD_POSTAL': '1423'}],
    ["Quiero asegurar un ford fiesta del 2019, mi código postal es 1418",
    {'MARCA': 'ford', 'MODELO': 'fiesta', 'AÑO': '2019', 'COD_POSTAL': '1418'}],
    ["Código postal 1427, necesito asegurar un hyundai creta del 2019",
    {'MARCA': 'hyundai', 'MODELO': 'creta', 'AÑO': '2019', 'COD_POSTAL': '1427'}],
    ["Vivo en el código postal 1438 y quiero asegurar un renault sandero del 2018",
    {'MARCA': 'renault', 'MODELO': 'sandero', 'AÑO': '2018', 'COD_POSTAL': '1438'}],
    ["Busco información para asegurar un fiat toro del 2018, mi código postal es 1435",
    {'MARCA': 'fiat', 'MODELO': 'toro', 'AÑO': '2018', 'COD_POSTAL': '1435'}],
    ["Mi código postal es 1406, necesito asegurar un honda fit del 2016",
    {'MARCA': 'honda', 'MODELO': 'fit', 'AÑO': '2016', 'COD_POSTAL': '1406'}],
    ["Quiero asegurar un chevrolet cruze del 2018, mi código postal es 1424",
    {'MARCA': 'chevrolet', 'MODELO': 'cruze', 'AÑO': '2018', 'COD_POSTAL': '1424'}],
    ["Código postal 1408, necesito asegurar un nissan kicks del 2020",
    {'MARCA': 'nissan', 'MODELO': 'kicks', 'AÑO': '2020', 'COD_POSTAL': '1408'}],
    ["Vivo en el código postal 1416 y quiero asegurar un ford focus del 2017",
    {'MARCA': 'ford', 'MODELO': 'focus', 'AÑO': '2017', 'COD_POSTAL': '1416'}],
    ["Busco información para asegurar un peugeot 2008 del 2016, mi código postal es 1420",
    {'MARCA': 'peugeot', 'MODELO': '2008', 'AÑO': '2016', 'COD_POSTAL': '1420'}],
    ["Mi código postal es 1432, necesito asegurar un toyota etios del 2017",
    {'MARCA': 'toyota', 'MODELO': 'etios', 'AÑO': '2017', 'COD_POSTAL': '1432'}]
]

print(len(training_data))
encontrar_posicion_regex(training_data)

"""
Formato 
 TRAIN_DATA = [(
    {"text": "buenas tardes, quisiera cotizar un seguro para mi auto por favor, envíenme las diferentes opciones que su compañia ofrece los datos de mi vehiculo son  marca chevrolet  modelo spin  año 2023 cod postal 1414  tengo cochera propia adjunto también foto de mi vehiculo para que se vea que está en perfectas condiciones muchas gracias", 
        "entities": [(108, 118, "MARCA"), (120, 124, "MODELO"), (126, 130, "AÑO"), (132, 140, "COD_POSTAL")]}
    )],
"""